services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=db_brm
      - DB_PORT=5432
    volumes:
      - .:/app
      - ./doc:/app/doc  
      - ./apidoc.json:/app/apidoc.json 
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=db_brm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: